services:
  automation-hub:
    image: ghcr.io/arui-tw/bots:latest
    container_name: automation-hub
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
